export const AUTH_SET_SERVER_ERROR = "AUTH/SET_SERVER_ERROR";
export const AUTH_SET_AUTH_IN_PROCESS = "AUTH/SET_AUTH_IN_PROCESS";
export const AUTH_SET_USER_AUTH = "AUTH/SET_USER_AUTH";

export const RECIPES_SET_FETCHING_IN_PROCESS =
  "RECIPES/SET_FETCHING_IN_PROCESS";
export const RECIPES_SET_SERVER_ERROR = "RECIPES/SET_SERVER_ERROR";
export const RECIPES_SET_RECIPES = "RECIPES/SET_RECIPES";
export const RECIPES_SET_DOCS_COUNT = "RECIPES/SET_DOCS_COUNT";
export const RECIPES_SET_CURRENT_PAGE = "RECIPES/SET_CURRENT_PAGE";
